"use strict";
exports.__esModule = true;
var route_users_populate_1 = require("./route_users_populate");
exports.populate = route_users_populate_1.populate;
var route_users_fetchFriends_1 = require("./route_users_fetchFriends");
exports.fetchFriends = route_users_fetchFriends_1.fetchFriends;
var route_friends_newFriend_1 = require("./route_friends_newFriend");
exports.newFriend = route_friends_newFriend_1.newFriend;
var route_users_fetchUsers_1 = require("./route_users_fetchUsers");
exports.fetchUsers = route_users_fetchUsers_1.fetchUsers;
var route_users_login_1 = require("./route_users_login");
exports.login = route_users_login_1.login;
var route_users_logout_1 = require("./route_users_logout");
exports.logout = route_users_logout_1.logout;
var route_users_registration_1 = require("./route_users_registration");
exports.registration = route_users_registration_1.registration;
var route_conv_newConversation_1 = require("./route_conv_newConversation");
exports.newConversation = route_conv_newConversation_1.newConversation;
var route_conv_fetchConversations_1 = require("./route_conv_fetchConversations");
exports.fetchConversations = route_conv_fetchConversations_1.fetchConversations;
var route_mess_fetchMessages_1 = require("./route_mess_fetchMessages");
exports.fetchMessages = route_mess_fetchMessages_1.fetchMessages;
var route_mess_saveMessage_1 = require("./route_mess_saveMessage");
exports.saveMessage = route_mess_saveMessage_1.saveMessage;
exports.index = function (req, res, next) {
    next();
};
