"use strict";
exports.__esModule = true;
var ROLE_MEMBER = 'Member';
exports.ROLE_MEMBER = ROLE_MEMBER;
var ROLE_CLIENT = 'Client';
exports.ROLE_CLIENT = ROLE_CLIENT;
var ROLE_OWNER = 'Owner';
exports.ROLE_OWNER = ROLE_OWNER;
var ROLE_ADMIN = 'Admin';
exports.ROLE_ADMIN = ROLE_ADMIN;
